### PR TITLE
Update the main project ReadMe

### PR DESCRIPTION
**Pull request by DundieWinner**
I spent many hours trying to figure out how to build Boolberry from source with no errors. I finally figured it out, and so I think sharing the detailed steps of how I did it will benefit others moving forward.

### CODE REVIEW

**Comment by 1blockologist** [comment]
Thanks, we will need testing on different environments going forward. What version of Windows were you using?

**Comment by DundieWinner** [comment]
Windows 8.1. I can also test on Windows 10 if you think that would be helpful

**Comment by 1blockologist** [comment]
Do you happen to have records of which errors you encountered and needed to solve with the more verbose paths?

This will also help for SEO

**Comment by DundieWinner** [comment]
I don't have a list of the errors right now but I could come up with one because I remember most of them.

**Comment by 1blockologist** [comment]
That would be helpful, just write a comment with the problems you encountered and I'll merge the pull request

**Review by 1blockologist — COMMENTED** [review]
Nice catch!

**Comment by 1blockologist** [comment]
In the future, open a separate pull request for separate issues, if it doesn't impact the merge

**Comment by DundieWinner** [comment]
That's my bad, sorry. I am still new to using Github. I'll get it figured out

**Comment by DundieWinner** [comment]
Some problems I occurred while trying to build Boolberry from source on a Windows 8:
- Building with cygwin or mysys2 is really the wrong approach because the cmake package that is installed   doesn't allow you to build with the Visual Studio compiler
- Visual Studio 2013 must be used because there are some methods used in our code that are specific to its compiler (i.e. Earlier and later versions will lead to a large amount of compilation errors)
- I downloaded the Boost 1.55 executable to install a prebuilt version of this library, but I found that it was leaving out some crucial libraries. For example, the serialization library was left out. This made it impossible to build Boolberry with this version of Boost. However, using Boost 1.56 worked well and that will be the library I continue to use moving forward.
- When you install Boost, inside the home directory there will be a folder called "lib64-msvc-12.0". I tried to direct cmake to this folder using "-DBOOST_LIBRARYDIR=...\lib64-msvc-12.0" but it couldn't find the static libraries. The solution to this problem is to rename the folder "lib64-msvc-12.0" to "lib". Then just use "-DBOOST_ROOT" to direct cmake to the root boost directory, and cmake will be able to find the static libraries.
- The command prompt will not find the msbuild executable if you are not in the VS2013 command prompt. This is because the VS command prompt sets up the necessary environment variables

**Comment by clintar** [comment]
Do you have an include folder after installing this binary boost? mine doesn't come with an include folder

**Comment by DundieWinner** [comment]
No, I do not have an include folder inside the boost folder. In the main boost director I have the following folders: boost, doc, lib, libs, more, status, tools

**Comment by clintar** [comment]
I don't see how you got this to compile. I just get 
```  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:120 (find_package)
```
Maybe it's because I used version 1.57.0

**Comment by 1blockologist** [comment]
Uninstall Boost 1.57 and try 1.56

I had inadvertently tried other combinations as well

Visual Studio 2013, Boost 1.56.

On OSX, there is no Visual Studio, but I was able to build with the command line. I never got the linking working in Xcode working, so that slowed me down.

On two Windows VPSs I've been able to build it also with the command line. While using a Visual Studio version to at least help me browse through the code and dependencies easily. I haven't  successfully compiled or debugged with an IDE at all yet.

**Comment by clintar** [comment]
Yeah, still problems. I think we might have downloaded different things. it sees the boost version, but doesn't find static libraries for boost_system, boost_filesystem, boost_thread, boost_date_time, boost_chrono, boost_regex, boost... etc.

**Comment by DundieWinner** [comment]
To confirm what was said above, yes you need to use Boost 1.56 with Visual Studio 2013. Using different boost versions made it impossible for me to compile.

I zipped up my Boost 1.56 folder for you. I know it's large but download it and compare it against yours: www.dropbox.com/s/bbltqd68xeawqwy/boost_1_56_0.zip

**Comment by clintar** [comment]
does the same thing using yours.

**Comment by DundieWinner** [comment]
I remember having the same error as you. I am racking my brain trying to remember how I fixed it.

**Comment by clintar** [comment]
I'm trying to run bootstrap.bat and .\b2
maybe it will compile the static libs, but i was reading before that i needed to set something to build 64bit. if this doesn't work, i'll look that up and try again.

**Pull request merged**
